language: swift
osx_image: xcode10.1
script:
  - swift package generate-xcodeproj --enable-code-coverage
  - xcodebuild -scheme CodableKit-Package -destination 'platform=macOS' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
