language: swift
osx_image: xcode9.4
script:
    - xcodebuild -scheme CodableKit -destination 'platform=iOS Simulator,name=iPhone X' -sdk iphonesimulator build test
after_success:
    - bash <(curl -s https://codecov.io/bash)
